modLoader="javafml"
loaderVersion="[48,)"
issueTrackerURL="https://github.com/Mrbysco/JustEnoughProfessions/issues"
license="MIT"

[[mods]]
modId="justenoughprofessions"
version="${file.jarVersion}"
displayName="Just Enough Professions (JEP)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep"
authors="Mrbysco, ShyNieke"
description='''
Adds info about professions to JEI
'''

[[dependencies.justenoughprofessions]]
modId="jei"
mandatory=true
versionRange="[16.0.0.28,)"
ordering="NONE"
side="BOTH"
[[dependencies.justenoughprofessions]]
modId="forge"
mandatory=true
versionRange="[48.0.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.justenoughprofessions]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"